name: Package Joy of Painting
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_NAME: JoyOfPainting
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Build Project
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a  ${{env.ARCHIVE_NAME}}.7z "Data Files"

      - name: Create Release
        uses: notlmn/release-with-changelog@v2
        with:
          header: '### Changelog'
          include-hash: true
          include-range: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{env.ARCHIVE_NAME}}.7z
